data:
  image: tianon/true
  volumes:
    - /contd/input   # git
    - /contd/output  # build output
    - /contd/logs    # console output

logspout:
  image: rtoma/logspout-redis-logstash:latest
  command: 'redis://redis'
  environment:
    - REDIS_KEY=logstash
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
  links:
    - redis

redis:
  image: redis:3.0.6
  environment:
    - LOGSPOUT=ignore
  ports:
    - 6379:6379

logstash:
  image: logstash:2.1.1-1
  command: logstash -f /logstash.conf
  environment:
    - LOGSPOUT=ignore
  ports:
    - 5000:5000
  links:
    - redis
  volumes_from:
    - data
  volumes:
    - /logstash.conf:/logstash.conf

nginx:
  image: nginx:1.9.10
  environment:
    - LOGSPOUT=ignore
  ports:
    - 8000:80
  volumes_from:
    - data
  volumes:
    - /nginx.conf:/etc/nginx/conf.d/default.conf:ro

#    - elasticsearch

#elasticsearch:
#  image: elasticsearch:2.1.1
#  # command: elasticsearch -Dnetwork.host=0.0.0.0
#  command: elasticsearch -Dnetwork.publish_host=188.166.136.103
#  environment:
#    - LOGSPOUT=ignore
#  ports:
#    - 9200:9200
#    - 9300:9300
#
# kibana:
#   image: kibana:4.3.1
#   environment:
#     - LOGSPOUT=ignore
#   ports:
#     - 5601:5601
#   links:
#     - elasticsearch
